const state = {
  config: null,
  session: null,
  user: null,
  files: [],
  rows: [],
  reservations: [],
  users: [],
  online: [],
  artworks: [],
  driveFolders: null,
  artworkSort: "desc",
  artworkViewMode: "cards",
  artworkTools: false,
  artworkSelection: new Set(),
  brokenArtworkImageIds: new Set(),
  currentFindArtworkId: "",
  uploadStartedAt: 0,
  mode: "standard",
  panel50ThemeTouched: false,
  financeItems: [],
  financePreview: [],
  financeClients: [],
  financeClientMatch: null,
  confirmResolver: null,
  bootstrap: null,
  cache: { artworksMap: {}, configs: {}, users: [] },
};
