const DEFAULT_GLOBAL_CONFIG = {
  operatorName: "Operador",
  credentialsPath: "",
  fixedDataFolder: "C:\\BancoDeArtes",
  panel50SourceRoot: "X:\\FESTAS E EVENTOS\\PAINEIS MARCKETPLACE\\SKUPR50 - PAINEIS REDONDOS 50 X 50\\SKUPR50 - IMPRESSÃO",
  panel50LastInputFolder: "",
  panel50OrganizedRoot: "X:\\1 - TEMAS ORGANIZADOS",
  panel50DriveLocalRoot: "X:\\2 - DRIVE",
  panel50MockupPath: "",
  financialClientRoot: "Z:\\2 - ARMAZEM FESTAS E EVENTOS",
  sessionTimeoutMinutes: 10,
  reservationTtlMinutes: 5,
  driveFolderBolinhas: "193kW8g7EsmrNwlGE3ugbC3qzOcDEwUae",
  driveFolderGeral: "1poSJTWYybZB1kvRwBK4ZnpVTMtHCpUfE",
  supabaseEnabled: true,
  supabaseUrl: "https://tviagmllvnhnrumhmeli.supabase.co",
  supabasePublishableKey: "sb_publishable_UVda8gD9YMptpWTfJLaeTA_3KJmBe-w",
  supabaseReadMode: "supabase",
  supabaseSchemaVersion: "2026-06-05-initial",
  supabaseAuthMode: "local",
  supabaseAuthEmailDomain: "bancodeartes.local",
  supabaseAdminUsersFunctionName: "admin-users",
  localImageFolders: ["imagens", "imagem"],
  acceptedExtensions: [".jpg", ".jpeg", ".jpe", ".png", ".webp", ".tif", ".tiff"],
  maintenanceMode: false,
  publicDriveUploads: true,
  allowManualBatch: true,
  validProducts: ["PAINEL REDONDO", "PAINEL", "CENARIO", "KIT", "ROMANO", "RETANGULO", "KIT MAIS ROMANO"],
  productSizes: {
    "PAINEL REDONDO": ["50X50"],
    PAINEL: ["50X50", "150X150"],
    CENARIO: ["150X360", "2X1"],
    KIT: ["PADRÃO"],
    ROMANO: ["150X360", "2X1"],
    RETANGULO: ["150X360", "2X1"],
    "KIT MAIS ROMANO": ["PADRÃO"]
  },
};

module.exports = {
  DEFAULT_GLOBAL_CONFIG,
};
