const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("artBank", {
  getConfig: () => ipcRenderer.invoke("config:get"),
  saveConfig: (config) => ipcRenderer.invoke("config:save", config),
  scanImages: (foldersOrRequest) => ipcRenderer.invoke("files:scan-images", foldersOrRequest),
  chooseImageFolder: () => ipcRenderer.invoke("files:choose-image-folder"),
  chooseMockupFile: () => ipcRenderer.invoke("files:choose-mockup-file"),
  openArtworkFolder: (payload) => ipcRenderer.invoke("files:open-artwork-folder", payload),
  recoverThumb: (path) => ipcRenderer.invoke("files:recover-thumb", path),
  validateBatch: (rows) => ipcRenderer.invoke("batch:validate", rows),
  parseFilenames: (files) => ipcRenderer.invoke("batch:parse-filenames", files),
  getProvisioningPlan: () => ipcRenderer.invoke("google:provisioning-plan"),
  getAuthStatus: () => ipcRenderer.invoke("google:auth-status"),
  authenticateGoogle: () => ipcRenderer.invoke("google:authenticate"),
  submitAuthCode: (code) => ipcRenderer.invoke("google:submit-auth-code", code),
  provisionGoogle: () => ipcRenderer.invoke("google:provision"),
  testConnectivity: () => ipcRenderer.invoke("google:test-connectivity"),
  listDriveFolders: (refresh) => ipcRenderer.invoke("google:drive-folders", refresh),
  supabaseStatus: () => ipcRenderer.invoke("supabase:status"),
  uploadBatch: (rows) => ipcRenderer.invoke("batch:upload", rows),
  runPanel50Batch: (payload) => ipcRenderer.invoke("photoshop:panel50-batch", payload),
  listFinanceClients: () => ipcRenderer.invoke("finance:clients"),
  previewFinanceOrder: (ids) => ipcRenderer.invoke("finance:preview", ids),
  copyFinanceOrder: (payload) => ipcRenderer.invoke("finance:copy-order", payload),
  onFinanceCopyProgress: (callback) => ipcRenderer.on("finance:copy-progress", (_event, payload) => callback(payload)),
  onUploadProgress: (callback) => ipcRenderer.on("batch:upload-progress", (_event, payload) => callback(payload)),
  bootstrapStatus: () => ipcRenderer.invoke("auth:bootstrap-status"),
  createAdmin: (payload) => ipcRenderer.invoke("auth:create-admin", payload),
  login: (payload) => ipcRenderer.invoke("auth:login", payload),
  currentSession: () => ipcRenderer.invoke("auth:current-session"),
  autoLoginDesktop: () => ipcRenderer.invoke("auth:auto-login-desktop"),
  logout: () => ipcRenderer.invoke("auth:logout"),
  heartbeat: (currentView) => ipcRenderer.invoke("auth:heartbeat", currentView),
  recordError: (payload) => ipcRenderer.invoke("errors:record", payload),
  onlineUsers: () => ipcRenderer.invoke("users:online"),
  listUsers: () => ipcRenderer.invoke("users:list"),
  createUser: (payload) => ipcRenderer.invoke("users:create", payload),
  setUserActive: (payload) => ipcRenderer.invoke("users:set-active", payload),
  updateUser: (payload) => ipcRenderer.invoke("users:update", payload),
  resetPassword: (payload) => ipcRenderer.invoke("users:reset-password", payload),
  deleteUser: (userId) => ipcRenderer.invoke("users:delete", userId),
  listReservations: () => ipcRenderer.invoke("reservations:list"),
  createReservation: (payload) => ipcRenderer.invoke("reservations:create", payload),
  releaseReservation: (id) => ipcRenderer.invoke("reservations:release", id),
  dashboardData: () => ipcRenderer.invoke("dashboard:data"),
  listArtworks: () => ipcRenderer.invoke("artworks:list"),
  updateArtwork: (payload) => ipcRenderer.invoke("artworks:update", payload),
  refreshArtworkUrl: (payload) => ipcRenderer.invoke("artworks:refresh-url", payload),
  deleteArtwork: (payload) => ipcRenderer.invoke("artworks:delete", payload),
  lockStatus: () => ipcRenderer.invoke("locks:status"),
  auditList: () => ipcRenderer.invoke("audit:list"),
  runSync: () => ipcRenderer.invoke("sync:run"),
  openExternal: (url) => ipcRenderer.invoke("app:open-external", url),
  listQuarantine: () => ipcRenderer.invoke("quarantine:list"),
  removeFromQuarantine: (id) => ipcRenderer.invoke("quarantine:remove", id),
});
